#!/usr/bin/env bash

iommu=(/sys/class/iommu/*)

if [ ! -e "${iommu[0]}" ] ; then
  rm -rf /etc/grub.d/*tboot*
fi

if [ -f "/run/platform-info/chassis_vendor_words/giada" ] ; then
  rm -rf /etc/grub.d/*tboot*
fi
