#!/usr/bin/env bash

. /root/fs-env

for d in ${BIOS_BOOTDEVS} ; do
  d=${d/[0-9]/}
  grub2-install "${d}"
done

# weird little bios bug
if [ -f /run/platform-info/bios_version_words/mrchromebox ] ; then
  cp /boot/efi/EFI/centos/grubx64.efi /boot/efi/EFI/BOOT/grubx64.efi
fi
